services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stagiaire
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend/backend
    container_name: backend
    restart: always
    depends_on:
      - mysql-db
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:
  backend_uploads:

networks:
  app-network: